### PR TITLE
Can't Add Custom Broadcast Layout Fix

### LINKED ISSUE #217: Can't Add Custom Broadcast Layout
Every time I try to add custom layout for my broadcast I get this error 

`type is not valid`

I traced the issue back in the code and found this 

`      valid_non_custom_type = ["bestFit","horizontalPresentation","pip", "verticalPresentation", ""].include? type`
   `   raise ArgumentError, "type is not valid" if !valid_non_custom_type`

in this file [https://github.com/opentok/OpenTok-Ruby-SDK/blob/master/lib/opentok/broadcasts.rb](url)

when i replaced this with this it worked fine 

`raise ArgumentError, "type is not valid" if !valid_non_custom_type && !(type.eql? "custom")`

### PR DESCRIPTION
**Pull request by Abdelrahman-Atia**
#217 
I added specs to clarify the fix, the second spec is failing on master which it shouldn't

Update: 
Same issues happen for the layout of the archive as the broadcast layout so I fix that too

### CODE REVIEW

**Comment by benhayehudi** [comment]
Thank you, @Abdelrahman-Atia for this PR! We'll take a look tomorrow, with the aim of moving forward on it. Your contribution is greatly appreciated! 🎉

**Comment by benhayehudi** [comment]
@Abdelrahman-Atia, just so you know we haven't forgotten about this. I've been digging trying to find out why the spec is failing in this instance. I worked with another teammate yesterday on that and will do again on Monday.

**Comment by Abdelrahman-Atia** [comment]
> @Abdelrahman-Atia, just so you know we haven't forgotten about this. I've been digging trying to find out why the spec is failing in this instance. I worked with another teammate yesterday on that and will do again on Monday.

@benhayehudi I'm glad to hear that
the thing is the old condition was ` raise ArgumentError, "type is not valid" if !valid_non_custom_type`
so if the type is custom and there is a stylesheet property provided this exception will trigger.
there was no specs to cover this case before. so we need to check if the type isn't custom here too.
hope this explains it

**Comment by benhayehudi** [comment]
> > @Abdelrahman-Atia, just so you know we haven't forgotten about this. I've been digging trying to find out why the spec is failing in this instance. I worked with another teammate yesterday on that and will do again on Monday.
> 
> @benhayehudi I'm glad to hear that
> the thing is the old condition was ` raise ArgumentError, "type is not valid" if !valid_non_custom_type`
> so if the type is custom and there is a stylesheet property provided this exception will trigger.
> there was no specs to cover this case before. so we need to check if the type isn't custom here too.
> hope this explains it

Yes, the issue is definitely present. What I am trying to do is figure out why the new specs keep on failing. I have been working to try and mock this method call, and I am getting back from the API different error codes depending on what I try. I have then tried to actually perform the custom broadcast layout in a sample application by both making the HTTP call directly, and with the OpenTok SDK. I can set the various pre-defined layouts, but I am having a hard time setting the custom layout with success. I have another meeting with one of the OpenTok specialists tomorrow afternoon to try and work through this. Hopefully we can resolve it this week.

**Comment by benhayehudi** [comment]
After some serious investigation, the solution was relatively straightforward. The spec was not properly mocking the HTTP requests to the API and so both the new spec and the existing one in this area were returning invalid responses, because they were live requests.

**Comment by Abdelrahman-Atia** [comment]
@benhayehudi  thank you very much!

**Pull request merged**
