### PR TITLE
Add HTTP default_timeout

### PR DESCRIPTION
**Pull request by dramalho**
Simply adds a default timeout (connect / read) to `HTTParty` to ensure clients don't get unexpected delays in case of network issues. 

I do think it's a very rare event, but given:
* HTTParty supports the option well enough
* There doesn't seem to be an easy way to set this from the outside of the class

I though I would just add the change and open a PR with you guys.

I'm not sure how to spec this out though, I could mock timeouts but that's probably not exactly what I want as it would just mock the exception and not the _actual_ waiting period.

Thoughts from you guys?

### CODE REVIEW

**Comment by aoberoi** [comment]
yikes, sorry for leaving this PR hanging for a little while. right after that praise too...

i hadn't thought about the difference between the connection timeout and the actual response body timeout. it sounds like HTTParty isn't thinking too hard about it either. Neither is WebMock.

i follow your reasoning on wanting to be more aggressive about the connection timeout, so i think 1s is a good value. i'd be happy to merge that change in.

in terms of testing, yeah i get that WebMock just throwing the exception, so its just a simulation. but i still think its worth demonstrating that a timeout error is properly addressed by wrapping it in an `OpenTokError`. so for that reason, i'd still like to see something in the specs about it. would you mind adding that in?

**Comment by dramalho** [comment]
:) No problem at all, I'll push some specs in. 

Incidentally, we've been running this off our fork and although it's extremely rare (<10 occurrences in the past 2 months) every now and then we do get a connection timeout exception and I'm very happy for the time out :)

I'll write some specs later on then, thanks

**Comment by dramalho** [comment]
So, a couple of things up for discussion:

* I added rescue blocks at each client operation to wrap the error around an OpetokError :
  * I initially though about adding one rescue block to the class, but I felt I would rather be specific, even if repetitive
  * I'm catching `StandardError`, reason being that errors classes might not be consistent, Webmock will force a `Timeout::Error`, while `HTTParty` should throw it's own `HTTParty::Error`, but if you swap client support it would be something else - my rationale was, at method level, any exception has to be http client related, so I figured I just catch `StandardError` 
* I added a couple of specs to OpenTok and Archive spec files - should I add a few more?

**Comment by matsubo** [comment]
+1

**Comment by aoberoi** [comment]
:+1 from me too

**Comment by dramalho** [comment]
hey great :)

**Pull request merged**
