### PR TITLE
 code coverage with coveralls.io #51 

### PR DESCRIPTION
**Pull request by tarasmatsyk**
- add gem to gemspec
- add require 'coveralls' to spec_helper
- specify service name in .coveralls.yml

The next time project builds on Travis simplecov should send data to coverall. 

> I am not sure whether coverall and simplecov could be used in gemspec or it would be better to leave them in Gemfile.

### CODE REVIEW

**Comment by tamatsyk** [comment]
this closes #51

**Comment by tamatsyk** [comment]
Hope I am not messing up the project. 
Am I doing something wrong in my pool requests?

**Comment by Lucashuang0802** [comment]
@tarasmatsyk Thanks so much for submitting it a long time ago. See if you have a chance to update it? 😃

**Comment by jeffswartz** [comment]
Closing due to inactivity.

**Pull request closed without merging**
