### PR TITLE
relax httparty dependencies

### PR DESCRIPTION
**Pull request by kimyu92**
- httparty [changelog](https://github.com/jnunemaker/httparty/blob/master/Changelog.md#0170)
- addressable [changelog](https://github.com/sporkmonger/addressable/blob/master/CHANGELOG.md)
- tigger travis CI build against ruby 2.5 and 2.6

### CODE REVIEW

**Comment by kimyu92** [comment]
Please feel free to review it. Thank you. cc @@msach22

**Comment by kimyu92** [comment]
@RaviAsnani Any thought on when would this be merged?

**Comment by RaviAsnani** [comment]
@kimyu92 Sorry I have no idea :) I'm not an approved reviewer or authorized to merge code. I've forked the code with this fix and been using it. When and if they merge it I'll move back.

**Comment by kimyu92** [comment]
@aiham @msach22 happy new year, would love to see this getting merged to support [ruby 2.6](https://github.com/jnunemaker/httparty/blob/master/Changelog.md#0164) and rails 6

**Comment by msach22** [comment]
Hi all, happy new year!

I don't maintain this repo anymore, but I've asked the team in charge to take a look. Hope to have some progress on this soon. Apologies for leaving this hanging.

**Comment by jeffswartz** [comment]
Thanks, @kimyu92 for your PR. We merged in a similar PR to update dependencies (https://github.com/opentok/OpenTok-Ruby-SDK/pull/192), and we will close this one.

**Pull request closed without merging**
