### PR TITLE
support activesupport 2 by requiring core_ext instead of time

### PR DESCRIPTION
**Pull request by jasquat**
If this gets merged we would love to see a new release of the gem with the change. Thanks.

### CODE REVIEW

**Comment by bencgreenberg** [comment]
Closing this as it's been 2 years since it's opened.

**Comment by burnettk** [comment]
@bencgreenberg , it's not going to break anything for existing users and it adds support more users. :) is there a different process one should follow to get patches adopted?

**Comment by bencgreenberg** [comment]
@burnettk, can you help me understand a bit more? It looks like activesupport v6.x has `core_ext/time` unless I'm missing something, which is definitely possible! :)

**Comment by burnettk** [comment]
it's relevant to activesupport v2. v3 introduces active_support/time. so on second thought, yeah, it's maybe not worth it on balance to support such old versions.

**Comment by bencgreenberg** [comment]
Yeah, it looks like v2 is back from 2009, if I'm reading the version history correctly. There's been a lot of changes in activesupport since then, so I think we'll pass on adding exception handling for something from 11 years ago. Thank you though for helping me think through this and apologies it took so long for someone to get back to you on it.

**Pull request closed without merging**
